### ISSUE TITLE
demo doesn't work

### ISSUE THREAD

**Issue by esromneb** [TomasHubelbauer/html-data-view-box#1]
I'm on chrome `Version 103.0.5060.53 (Official Build) (arm64)` and when I load the demo the page doesn't seem to load. Not sure what but it feels like the js is hanging

**Comment by TomasHubelbauer** [comment]
Hey! Thanks for the bug report. I pushed in a couple of fixes. Unfortunately, the virtualization of the web component doesn't quite work at the moment. If you were hoping to use it for its virtualized nature, you might want to look for something more production ready.

The problem is that in the virtualized mode (without the `no-virtualization` HTML attribute) the component renders the exact amount of rows needed to cover the viewport, and not rows for all of the rows in the underlying data view.

In order to make scrolling work, I attempt to tweak top and bottom padding such that when you scroll, the padding negates the offset of the scroll such that the N rows to cover the viewport remain pinned in place so that you never see the dead space above or below them as you scroll. At the same time, while scrolling, the content of these rows updates so that the virtual row that is pinned in place always reflects the content of the would-be physical row corresponding to the data view at that scroll position. This is the gist of the virtualization logic, but due to some off-by-one or something along those lines, when the padding is applied, it is ever so slightly off and it causes the whole list to drift off slowly.

Fixing this is just a matter of figuring out how to bridge this gap between the exact amount of padding needed and the amount of padding I currently calculate, but I have not managed that yet. Feel free to take a stab at it if you like.

Let me know if I can help.

**Comment by esromneb** [comment]
Well the demo is working now, so good job! I'm not sure if I want the virtualization html attribute or not. I'll look into it some more.  Thanks for the quick reply.
